version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 5

  test:
    build:
      dockerfile: testing-dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    command: ["poetry", "run", "python", "run_tests.py"]
